### ISSUE TITLE
Haxe 3 Syntax Support

### ISSUE THREAD

**Issue by darmie** [Danielku15/java2haxe#10]
Hi, I want to convert an existing Java source to Haxe. But this repository seem to be 4 years old and I need it to transform the source to a Haxe 3 source.

**Comment by Danielku15** [comment]
Hi. This project never really came to the state that is is usable and will likely never come. I started it some years ago as a trial to create a Java to Haxe converter but I never finalized it.

**Comment by darmie** [comment]
Ok. Thanks.
